//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketeiraWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhone
    {
        public int UserPhoneId { get; set; }
        public int UserId { get; set; }
        public int PhoneNumber { get; set; }
        public int PhoneTypeId { get; set; }
    
        public virtual PhoneType PhoneType { get; set; }
        public virtual Users Users { get; set; }
    }
}
